// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoACiX2XI2UJiOz9kkeOeAX6wdhkqcqcM',
    appId: '1:884947998087:web:b3839e0709bc4f99beef22',
    messagingSenderId: '884947998087',
    projectId: 'ostad-batch-four',
    authDomain: 'ostad-batch-four.firebaseapp.com',
    storageBucket: 'ostad-batch-four.firebasestorage.app',
    measurementId: 'G-941NE32158',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhKg1pbcWu0qMbE9U69i5lDgyO3W1l1g4',
    appId: '1:884947998087:android:8ae080c569922c58beef22',
    messagingSenderId: '884947998087',
    projectId: 'ostad-batch-four',
    storageBucket: 'ostad-batch-four.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OAQdaljYssfJIBoNsheL2Fpvnt0ax_s',
    appId: '1:884947998087:ios:67133b6453fcf8a5beef22',
    messagingSenderId: '884947998087',
    projectId: 'ostad-batch-four',
    storageBucket: 'ostad-batch-four.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6OAQdaljYssfJIBoNsheL2Fpvnt0ax_s',
    appId: '1:884947998087:ios:67133b6453fcf8a5beef22',
    messagingSenderId: '884947998087',
    projectId: 'ostad-batch-four',
    storageBucket: 'ostad-batch-four.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoACiX2XI2UJiOz9kkeOeAX6wdhkqcqcM',
    appId: '1:884947998087:web:85a368af24ca32e2beef22',
    messagingSenderId: '884947998087',
    projectId: 'ostad-batch-four',
    authDomain: 'ostad-batch-four.firebaseapp.com',
    storageBucket: 'ostad-batch-four.firebasestorage.app',
    measurementId: 'G-JSLW07KK1M',
  );
}